#include "arc/arc2/runtime.hpp"
#include "arc/arc2/bridge.hpp"
#include <array>
#include <cassert>
#include <iostream>

using namespace arc::arc2;
int main() {
    Runtime r(64,64);
    auto device=r.create_object(ObjectKind::Device,1);
    auto queue=r.create_object(ObjectKind::Queue,2);
    auto list=r.create_object(ObjectKind::CommandList,3);
    auto allocator=r.create_object(ObjectKind::Allocator,4);
    auto heap=r.create_object(ObjectKind::DescriptorHeap,5);
    auto resource=r.create_object(ObjectKind::Resource,6);
    r.describe_resource(resource,4096);
    assert(r.find_object(6)==resource);
    r.destroy_object(resource);
    assert(!r.find_object(6));
    auto reused=r.create_object(ObjectKind::Resource,6);
    assert(reused!=resource);
    r.describe_resource(reused,8192);
    ResourceShape shape; shape.dimension=ResourceDimension::Texture2D; shape.allocation=ResourceAllocation::Committed; shape.width=64; shape.height=32; shape.array_layers=1; shape.mips=4; shape.format=28; shape.samples=1; shape.format_namespace=1;
    r.describe_resource_shape(reused,shape);
    auto ref=r.write_descriptor(heap,0,reused,ViewKind::Rtv);
    auto copied=r.copy_descriptor(heap,1,ref);
    assert(copied.generation==1);
    auto overwritten=r.write_descriptor(heap,0,reused,ViewKind::Srv);
    assert(overwritten.generation==2);
    r.reset_command_list(list,allocator);
    std::array<std::uint32_t,5> color{1,2,3,4,0};
    assert(!r.record_clear(list,copied,color));
    assert(r.record_clear(list,copied,color));
    auto last=r.last_work(list); assert(last && last->rewrite_eligible);
    r.touch_command(list);
    assert(!r.record_clear(list,copied,color));
    r.set_root_table(list,false,0,overwritten);
    auto draw=r.record_work(list,WorkKind::Draw); assert(draw.value);
    r.close_command_list(list);
    auto sub=r.submit(queue,std::array<ObjectId,1>{list}); assert(sub.value);
    auto fence=r.create_object(ObjectKind::Fence,7);
    r.signal(queue,fence,8);
    auto queue2=r.create_object(ObjectKind::Queue,8);
    r.wait(queue2,fence,8);
    r.reset_command_list(list,allocator);
    r.barrier(list,reused,1,2);
    r.close_command_list(list);
    auto sub2=r.submit(queue2,std::array<ObjectId,1>{list});
    auto swap=r.create_object(ObjectKind::Swapchain,9);
    r.present(swap,queue2,reused,0);
    r.resize_swapchain(swap);
    r.present(swap,queue2,reused,0);
    auto ir=r.snapshot();
    assert(ir.submissions.size()==2 && ir.submissions.back().dependencies.front()==sub);
    assert(ir.presents.size()==2 && ir.presents.back().swapchain_generation==1);
    assert(ir.total_work==5 && ir.dropped==0);
    assert(serialize(ir)==serialize(r.snapshot()));
    arc::ResourceGraph graph;
    feed_resource_graph(ir,graph);
    assert(graph.errors()==0);
    assert(graph.workload_totals().submissions==2);
    assert(graph.find(reused.value) && graph.find(reused.value)->read_count+graph.find(reused.value)->write_count>0);
    assert(graph.find(reused.value)->description.kind==arc::ResourceKind::Texture2D);
    assert(graph.find(reused.value)->description.width==64 && graph.find(reused.value)->description.height==32 && graph.find(reused.value)->description.mip_levels==4);
    assert(graph.presentation_frame()==2);
    Runtime deferred;
    auto dq=deferred.create_object(ObjectKind::Queue,70);
    auto sq=deferred.create_object(ObjectKind::Queue,71);
    auto df=deferred.create_object(ObjectKind::Fence,72);
    deferred.wait(dq,df,9);
    assert(deferred.snapshot().incomplete && !deferred.snapshot().fences.front().satisfied);
    auto sl=deferred.create_object(ObjectKind::CommandList,73);
    deferred.close_command_list(sl);
    auto future=deferred.submit(sq,std::array<ObjectId,1>{sl});
    deferred.signal(sq,df,9);
    assert(!deferred.snapshot().incomplete && deferred.snapshot().fences.front().satisfied);
    assert(deferred.snapshot().fences.front().submission==future);
    auto dependent=deferred.submit(dq,std::array<ObjectId,1>{sl});
    assert(deferred.snapshot().submissions.back().dependencies.front()==future);
    (void)dependent;
    // State snapshots own root constants and preserve same-signature bindings.
    Runtime state;
    auto l=state.create_object(ObjectKind::CommandList,20);
    auto pso=state.create_object(ObjectKind::PipelineState,21);
    auto root=state.create_object(ObjectKind::RootSignature,22);
    auto root2=state.create_object(ObjectKind::RootSignature,23);
    FixedPipelineState fixed; fixed.raster_fill=1; fixed.raster_cull=3; fixed.raster_known=true; fixed.depth_enable=true; fixed.depth_func=4; fixed.depth_known=true; fixed.targets[0].write_mask=15; fixed.blend_known=true; fixed.topology_type=3; fixed.topology_known=true;
    state.describe_pipeline_fixed(pso,fixed);
    state.set_pipeline(l,pso);
    state.set_viewports(l,std::array<Viewport,1>{Viewport{0,0,640,480,0,1}});
    state.set_topology(l,3);
    state.set_blend_factor(l,{1,0,0,1});
    state.set_stencil_ref(l,7);
    state.set_root_signature(l,root,false);
    std::array<std::uint32_t,2> constants{11,22};
    state.set_root_constants(l,false,0,0,constants);
    state.set_root_signature(l,root,false);
    state.record_work(l,WorkKind::Draw);
    constants[0]=99;
    state.set_root_constants(l,false,0,0,constants);
    state.record_work(l,WorkKind::Draw);
    auto captured=state.snapshot();
    assert(captured.work[0].state.graphics_bindings.at(0).constants[0]==11);
    assert(captured.work[1].state.graphics_bindings.at(0).constants[0]==99);
    assert(captured.work[0].state.fixed.raster_cull==3 && captured.work[0].state.raster_known);
    assert(captured.work[0].state.viewports.front().width==640 && captured.work[0].state.stencil_ref==7);
    auto serialized=serialize(captured);
    assert(serialized.find("[0,2,0,0,0,0,0,[11,22],null]")!=std::string::npos);
    assert(serialized.find("[0,2,0,0,0,0,0,[99,22],null]")!=std::string::npos);
    state.set_root_signature(l,root2,false);
    state.record_work(l,WorkKind::Draw);
    assert(state.snapshot().work[2].state.graphics_bindings.empty());
    state.execute_bundle(l,l);
    assert(state.snapshot().work.back().accesses.front().certainty==Certainty::Symbolic);
    auto shader=state.create_object(ObjectKind::Shader,24);
    Access dynamic{{},AccessKind::Read,Certainty::Symbolic,0,0,"space1:t0[dynamic]"};
    state.describe_shader(shader,std::array<Access,1>{dynamic});
    state.set_pipeline_shaders(pso,std::array<ObjectId,1>{shader});
    state.set_pipeline(l,pso);
    state.record_work(l,WorkKind::Dispatch);
    auto shader_ir=state.snapshot();
    assert(shader_ir.work.back().accesses.front().certainty==Certainty::Symbolic);
    assert(shader_ir.shaders.size()==1 && serialize(shader_ir).find("space1:t0[dynamic]")!=std::string::npos);
    Runtime ranges;
    auto rl=ranges.create_object(ObjectKind::CommandList,50);
    auto rr=ranges.create_object(ObjectKind::RootSignature,51);
    auto rh=ranges.create_object(ObjectKind::DescriptorHeap,52);
    auto rs=ranges.create_object(ObjectKind::Shader,53);
    auto rp=ranges.create_object(ObjectKind::PipelineState,54);
    ranges.describe_descriptor_heap(rh,10);
    RootParameter parameter; parameter.slot=0; parameter.kind=RootParameterKind::Table;
    parameter.ranges={{BindingKind::Srv,1,4,3,2},{BindingKind::Srv,1,7,2,UINT32_MAX}};
    ranges.describe_root_signature(rr,std::array<RootParameter,1>{parameter});
    ranges.describe_shader(rs,{});
    ranges.describe_shader_bindings(rs,std::array<ShaderBinding,1>{ShaderBinding{BindingKind::Srv,1,5,4,true,AccessKind::Read}});
    ranges.set_pipeline_shaders(rp,std::array<ObjectId,1>{rs});
    ranges.set_pipeline(rl,rp);
    ranges.set_root_signature(rl,rr,false);
    ranges.set_root_table(rl,false,0,DescriptorRef{rh,0,0});
    ranges.record_work(rl,WorkKind::Draw);
    auto mapped=ranges.snapshot().work.back().accesses;
    assert(mapped.size()>=2 && mapped[0].certainty==Certainty::Symbolic && mapped[0].descriptor_heap==rh);
    assert(mapped[0].descriptor_first==3 && mapped[0].descriptor_count==2);
    assert(mapped[1].descriptor_first==5 && mapped[1].descriptor_count==2);
    assert(serialize(ranges.snapshot()).find("\"root_signatures\"")!=std::string::npos);
    // An overflowing table range stays unknown, never clipped into evidence.
    ranges.set_root_table(rl,false,0,DescriptorRef{rh,9,0});
    ranges.record_work(rl,WorkKind::Draw);
    assert(ranges.snapshot().work.back().accesses[0].certainty==Certainty::Unknown);
    // A reflected b0 CBV can be supplied by inline root constants. The value
    // is captured, but it creates no GPU resource dependency.
    Runtime inline_constants;
    auto ic_list=inline_constants.create_object(ObjectKind::CommandList,90);
    auto ic_root=inline_constants.create_object(ObjectKind::RootSignature,91);
    auto ic_shader=inline_constants.create_object(ObjectKind::Shader,92);
    auto ic_pso=inline_constants.create_object(ObjectKind::PipelineState,93);
    RootParameter ic_param; ic_param.slot=2; ic_param.kind=RootParameterKind::Constants; ic_param.descriptor_kind=BindingKind::Cbv; ic_param.space=0; ic_param.shader_register=0; ic_param.constant_count=1;
    inline_constants.describe_root_signature(ic_root,std::array<RootParameter,1>{ic_param});
    inline_constants.describe_shader(ic_shader,{});
    inline_constants.describe_shader_bindings(ic_shader,std::array<ShaderBinding,1>{ShaderBinding{BindingKind::Cbv,0,0,1,false,AccessKind::Read}});
    inline_constants.set_pipeline_shaders(ic_pso,std::array<ObjectId,1>{ic_shader});
    inline_constants.set_pipeline(ic_list,ic_pso);
    inline_constants.set_root_signature(ic_list,ic_root,true);
    inline_constants.set_root_constants(ic_list,true,2,0,std::array<std::uint32_t,1>{17});
    inline_constants.record_work(ic_list,WorkKind::Dispatch);
    auto inline_work=inline_constants.snapshot().work.back();
    assert(inline_work.accesses.empty());
    assert(inline_work.state.compute_bindings.at(2).constants.at(0)==17);
    // A descriptor changed after recording invalidates submitted access evidence.
    Runtime stale;
    auto q=stale.create_object(ObjectKind::Queue,30);
    auto c=stale.create_object(ObjectKind::CommandList,31);
    auto h=stale.create_object(ObjectKind::DescriptorHeap,32);
    auto res=stale.create_object(ObjectKind::Resource,33);
    auto d=stale.write_descriptor(h,0,res,ViewKind::Rtv);
    stale.set_targets(c,std::array<DescriptorRef,1>{d});
    stale.record_work(c,WorkKind::Draw);
    stale.close_command_list(c);
    stale.write_descriptor(h,0,res,ViewKind::Rtv);
    stale.submit(q,std::array<ObjectId,1>{c});
    auto invalid=stale.snapshot();
    assert(invalid.uncertain_submissions==1 && !invalid.submissions.front().complete);
    assert(invalid.work.front().supported);
    // Unmodeled commands permanently prohibit list-local clear elision until reset.
    Runtime poison;
    auto pl=poison.create_object(ObjectKind::CommandList,40);
    auto ph=poison.create_object(ObjectKind::DescriptorHeap,41);
    auto pr=poison.create_object(ObjectKind::Resource,42);
    auto pd=poison.write_descriptor(ph,0,pr,ViewKind::Rtv);
    poison.unsupported(pl,"SetPredication");
    assert(!poison.record_clear(pl,pd,color));
    assert(!poison.record_clear(pl,pd,color));
    poison.reset_command_list(pl,{});
    assert(!poison.record_clear(pl,pd,color));
    assert(poison.record_clear(pl,pd,color));
    Runtime bounded(1,1);
    auto b=bounded.create_object(ObjectKind::CommandList,10);
    bounded.record_work(b,WorkKind::Draw);
    bounded.record_work(b,WorkKind::Draw);
    assert(bounded.snapshot().dropped==1 && bounded.snapshot().incomplete);
    Runtime rolling(1,2);
    auto roll=rolling.create_object(ObjectKind::CommandList,60);
    rolling.record_work(roll,WorkKind::Draw);
    rolling.reset_command_list(roll,{});
    rolling.record_work(roll,WorkKind::Draw);
    auto rolled=rolling.snapshot();
    assert(rolled.total_work==2 && rolled.work.size()==1 && rolled.work.front().id.value==2);
    assert(rolled.history_truncated && !rolled.incomplete);
    Runtime invalid_access;
    auto il=invalid_access.create_object(ObjectKind::CommandList,80);
    auto irsrc=invalid_access.create_object(ObjectKind::Resource,81);
    invalid_access.describe_resource(irsrc,16);
    Access out_of_bounds{irsrc,AccessKind::Read,Certainty::Known,12,8};
    invalid_access.record_work(il,WorkKind::Copy,std::array<Access,1>{out_of_bounds});
    assert(invalid_access.snapshot().incomplete);
    assert(invalid_access.snapshot().work.front().accesses.front().certainty==Certainty::Unknown);
    (void)device;(void)sub2;
    std::cout<<"ARC2 IR tests passed\n";
}
