#include <windows.h>
#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <dxcapi.h>
#include <wrl/client.h>
#include "generic_shader_transform.hpp"
#include "generic_binding_state.hpp"
#include "generic_gpu_control.hpp"
#include "generic_edge_transform.hpp"
#include "generic_mip_transform.hpp"
#include <iostream>
#include <stdexcept>
#include <vector>
#include <cstring>
#include <filesystem>
using Microsoft::WRL::ComPtr;
using arc::dx12::optimizer::GpuControl;
void check(bool ok,const char* message){if(!ok)throw std::runtime_error(message);}
void hr(HRESULT value){check(SUCCEEDED(value),"D3D12/DXC failure");}
ComPtr<IDxcBlob> result(IDxcOperationResult* op){HRESULT status{};hr(op->GetStatus(&status));if(FAILED(status)){ComPtr<IDxcBlobEncoding> errors;op->GetErrorBuffer(&errors);if(errors)std::cerr.write(static_cast<const char*>(errors->GetBufferPointer()),errors->GetBufferSize());}hr(status);ComPtr<IDxcBlob> blob;hr(op->GetResult(&blob));return blob;}
int wmain(int argc,wchar_t** argv)try{
    check(argc==2||argc==3,"Absolute DXC DLL and optional --spatial required");const bool center=argc==3&&std::wstring(argv[2])==L"--spatial-center";const bool mip=argc==3&&std::wstring(argv[2])==L"--spatial-mip";const bool spatial=center||mip||(argc==3&&std::wstring(argv[2])==L"--spatial");const std::filesystem::path compiler_path=argv[1];
    auto validator_module=LoadLibraryExW((compiler_path.parent_path()/L"dxil.dll").c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);
    auto compiler_module=LoadLibraryExW(compiler_path.c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);check(compiler_module&&validator_module,"Load compiler");
    auto create=reinterpret_cast<DxcCreateInstanceProc>(GetProcAddress(compiler_module,"DxcCreateInstance"));auto create_validator=reinterpret_cast<DxcCreateInstanceProc>(GetProcAddress(validator_module,"DxcCreateInstance"));
    ComPtr<IDxcLibrary> library;ComPtr<IDxcCompiler> compiler;ComPtr<IDxcAssembler> assembler;ComPtr<IDxcValidator> validator;
    hr(create(CLSID_DxcLibrary,IID_PPV_ARGS(&library)));hr(create(CLSID_DxcCompiler,IID_PPV_ARGS(&compiler)));hr(create(CLSID_DxcAssembler,IID_PPV_ARGS(&assembler)));hr(create_validator(CLSID_DxcValidator,IID_PPV_ARGS(&validator)));
    const std::string source=mip?"Texture2D<float4> Input:register(t0); SamplerState S:register(s0); RWTexture2D<float4> Output:register(u0); [numthreads(8,8,1)] void main(uint3 p:SV_DispatchThreadID){Output[p.xy]=Input.Load(int3(p.xy,0))*float4(p.x,p.y,1,1)+Input.SampleLevel(S,(float2(p.xy)+.5)/16,0);}":spatial?"Texture2D<float4> Input:register(t0); RWTexture2D<float4> Output:register(u0); [numthreads(8,8,1)] void main(uint3 p:SV_DispatchThreadID){Output[p.xy]=Input.Load(int3(p.xy,0))*float4(p.x,p.y,1,1);}":"RWTexture2D<float4> Output:register(u0); [numthreads(8,8,1)] void main(uint3 p:SV_DispatchThreadID){Output[p.xy]=float4(p.x,p.y,0,1);}";
    ComPtr<IDxcBlobEncoding> text;hr(library->CreateBlobWithEncodingOnHeapCopy(source.data(),UINT(source.size()),CP_UTF8,&text));ComPtr<IDxcOperationResult> op;hr(compiler->Compile(text.Get(),L"marker",L"main",L"cs_6_0",nullptr,0,nullptr,0,nullptr,&op));auto original=result(op.Get());
    ComPtr<IDxcBlobEncoding> ir;hr(compiler->Disassemble(original.Get(),&ir));auto transformed=arc::dx12::shader::coarse_compute({static_cast<const char*>(ir->GetBufferPointer()),ir->GetBufferSize()},1,1,true,1,true);
    if(spatial){auto edge=arc::dx12::shader::protect_input_edges(transformed.ir,transformed);check(edge.input_mask==1,"Spatial input correspondence");transformed.ir=std::move(edge.ir);}
    if(mip){auto biased=arc::dx12::shader::bias_explicit_mips(transformed.ir);check(biased.samples==1,"Spatial mip sample");transformed.ir=std::move(biased.ir);}
    check(transformed.admitted&&transformed.execution_marker,"Marker transform admission");text.Reset();hr(library->CreateBlobWithEncodingOnHeapCopy(transformed.ir.data(),UINT(transformed.ir.size()),CP_UTF8,&text));op.Reset();hr(assembler->AssembleToContainer(text.Get(),&op));auto code=result(op.Get());op.Reset();hr(validator->Validate(code.Get(),DxcValidatorFlags_InPlaceEdit,&op));code=result(op.Get());
    ComPtr<ID3D12Debug> debug;hr(D3D12GetDebugInterface(IID_PPV_ARGS(&debug)));debug->EnableDebugLayer();ComPtr<ID3D12Device> device;hr(D3D12CreateDevice(nullptr,D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device)));ComPtr<ID3D12InfoQueue> diagnostics;hr(device.As(&diagnostics));
    D3D12_DESCRIPTOR_RANGE ranges[]{{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,1,0,0,1}};D3D12_ROOT_PARAMETER parameter{};parameter.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;parameter.DescriptorTable={spatial?2u:1u,ranges};D3D12_ROOT_SIGNATURE_DESC rd{1,&parameter,0,nullptr,D3D12_ROOT_SIGNATURE_FLAG_NONE};D3D12_STATIC_SAMPLER_DESC sampler{};sampler.Filter=D3D12_FILTER_MIN_MAG_MIP_POINT;sampler.AddressU=sampler.AddressV=sampler.AddressW=D3D12_TEXTURE_ADDRESS_MODE_CLAMP;sampler.MaxLOD=D3D12_FLOAT32_MAX;sampler.ComparisonFunc=D3D12_COMPARISON_FUNC_ALWAYS;sampler.ShaderVisibility=D3D12_SHADER_VISIBILITY_ALL;if(mip){rd.NumStaticSamplers=1;rd.pStaticSamplers=&sampler;}ComPtr<ID3DBlob> root_blob;hr(D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&root_blob,nullptr));
    auto bytes=arc::dx12::binding::append_control_cbv({static_cast<const std::byte*>(root_blob->GetBufferPointer()),root_blob->GetBufferSize()},1,true);check(!bytes.empty(),"Root marker extension");ComPtr<ID3D12RootSignature> root;hr(device->CreateRootSignature(0,bytes.data(),bytes.size(),IID_PPV_ARGS(&root)));
    D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.CS={code->GetBufferPointer(),code->GetBufferSize()};ComPtr<ID3D12PipelineState> pipeline;hr(device->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pipeline)));
    D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC td{};td.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;td.Width=td.Height=16;td.DepthOrArraySize=td.MipLevels=td.SampleDesc.Count=1;td.Format=DXGI_FORMAT_R32G32B32A32_FLOAT;td.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;
    ComPtr<ID3D12Resource> output;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&output)));D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.NumDescriptors=2;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;ComPtr<ID3D12DescriptorHeap> heap;hr(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));device->CreateUnorderedAccessView(output.Get(),nullptr,nullptr,heap->GetCPUDescriptorHandleForHeapStart());
    D3D12_RESOURCE_DESC bd{};bd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;bd.Width=8;bd.Height=bd.DepthOrArraySize=bd.MipLevels=bd.SampleDesc.Count=1;bd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;hp.Type=D3D12_HEAP_TYPE_UPLOAD;ComPtr<ID3D12Resource> predicate;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&bd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&predicate)));void* mapped{};D3D12_RANGE empty{};hr(predicate->Map(0,&empty,&mapped));std::memset(mapped,0,8);predicate->Unmap(0,nullptr);
    D3D12_COMMAND_QUEUE_DESC qd{};ComPtr<ID3D12CommandQueue> queue,other;hr(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)));hr(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&other)));
    ComPtr<ID3D12Resource> input,input_upload,pixels;
    if(spatial){hp.Type=D3D12_HEAP_TYPE_DEFAULT;td.Flags=D3D12_RESOURCE_FLAG_NONE;td.MipLevels=mip?2:1;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,nullptr,IID_PPV_ARGS(&input)));
        hp.Type=D3D12_HEAP_TYPE_UPLOAD;bd.Width=8192;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&bd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&input_upload)));
        hp.Type=D3D12_HEAP_TYPE_READBACK;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&bd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&pixels)));
        auto handle=heap->GetCPUDescriptorHandleForHeapStart();handle.ptr+=device->GetDescriptorHandleIncrementSize(hd.Type);D3D12_SHADER_RESOURCE_VIEW_DESC view{};view.Format=td.Format;view.ViewDimension=D3D12_SRV_DIMENSION_TEXTURE2D;view.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;view.Texture2D.MipLevels=mip?2:1;device->CreateShaderResourceView(input.Get(),&view,handle);}
    GpuControl control(device.Get(),false,spatial);ComPtr<ID3D12CommandAllocator> allocator;ComPtr<ID3D12GraphicsCommandList> list;hr(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)));hr(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),pipeline.Get(),IID_PPV_ARGS(&list)));hr(list->Close());
    ComPtr<ID3D12Fence> done;hr(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&done)));HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);UINT64 serial{};
    std::vector<GpuControl::ExecutionReadback> held;
    for(unsigned iteration=0;iteration<(spatial?9u:4u);++iteration){hr(allocator->Reset());hr(list->Reset(allocator.Get(),pipeline.Get()));
        if(spatial){hr(input_upload->Map(0,&empty,&mapped));for(unsigned i=0;i<1024;++i)static_cast<float*>(mapped)[i]=iteration==6?((i/4)%16<8?.125f:.875f):iteration>=7?.125f:iteration>=4?.75f:.25f;if(mip)for(unsigned i=1024;i<2048;++i)static_cast<float*>(mapped)[i]=.5f;input_upload->Unmap(0,nullptr);
            D3D12_RESOURCE_BARRIER barrier{};barrier.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;barrier.Transition={input.Get(),D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_DEST};list->ResourceBarrier(1,&barrier);D3D12_TEXTURE_COPY_LOCATION destination{},source{};destination.pResource=input.Get();destination.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;source.pResource=input_upload.Get();source.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;source.PlacedFootprint.Footprint={DXGI_FORMAT_R32G32B32A32_FLOAT,16,16,1,256};list->CopyTextureRegion(&destination,0,0,0,&source,nullptr);if(mip){destination.SubresourceIndex=1;source.PlacedFootprint.Offset=4096;source.PlacedFootprint.Footprint.Width=source.PlacedFootprint.Footprint.Height=8;list->CopyTextureRegion(&destination,0,0,0,&source,nullptr);}std::swap(barrier.Transition.StateBefore,barrier.Transition.StateAfter);list->ResourceBarrier(1,&barrier);}
        list->SetComputeRootSignature(root.Get());ID3D12DescriptorHeap* heaps[]{heap.Get()};list->SetDescriptorHeaps(1,heaps);list->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());list->SetComputeRootConstantBufferView(1,control.address(0));list->SetComputeRootUnorderedAccessView(2,control.marker_address(0));
        if(!spatial&&iteration==1)list->SetPredication(predicate.Get(),0,D3D12_PREDICATION_OP_EQUAL_ZERO);
        list->Dispatch(2,2,1);list->SetPredication(nullptr,0,D3D12_PREDICATION_OP_EQUAL_ZERO);control.marker_barrier(list.Get());
        if(spatial){D3D12_RESOURCE_BARRIER barrier{};barrier.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;barrier.Transition={output.Get(),0,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE};list->ResourceBarrier(1,&barrier);D3D12_TEXTURE_COPY_LOCATION destination{},source{};destination.pResource=pixels.Get();destination.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;destination.PlacedFootprint.Footprint={DXGI_FORMAT_R32G32B32A32_FLOAT,16,16,1,256};source.pResource=output.Get();source.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;list->CopyTextureRegion(&destination,0,0,0,&source,nullptr);std::swap(barrier.Transition.StateBefore,barrier.Transition.StateAfter);list->ResourceBarrier(1,&barrier);}
        control.record_neutralize(list.Get());hr(list->Close());
        arc::dx12::optimizer::ControlValue value{2,1,16,16};value.proof_epoch=UINT64(0x1234567800000000)+iteration+1;value.proof_pipeline=UINT64(0x8765432100000042);
        if(mip){value.x=value.y=1;value.mip_steps=2;}if(center&&iteration==1)value.spatial_center=1;
        if(spatial){value.edge_sources=0x80000001u;value.edge_threshold=.1f;value.spatial_key=iteration>=2?UINT64(0x200000011):UINT64(0x100000011);value.reserved=42;if(iteration>=7)value.spatial_frame=93+iteration;value.spatial_tile_width=value.spatial_tile_height=16;}
        auto* helper=control.prepare(queue.Get(),{&value,1});check(helper,"Free proof ring slot");queue->ExecuteCommandLists(1,&helper);ID3D12CommandList* work[]{list.Get()};queue->ExecuteCommandLists(1,work);control.submitted(queue.Get());hr(queue->Signal(done.Get(),++serial));hr(done->SetEventOnCompletion(serial,event));check(WaitForSingleObject(event,5000)==WAIT_OBJECT_0,"GPU completion");
        check(!control.execution_readback(other.Get()),"Other queue cannot claim execution");auto proof=control.execution_readback(queue.Get());check(bool(proof),"Readback witness");std::array<std::array<UINT64,2>,GpuControl::capacity> actual{};std::array<std::array<UINT,2>,GpuControl::capacity> counts{};check(proof->read(actual,&counts),"Completed witness");check((actual[0]==proof->expected[0])==(spatial||iteration!=1),"Only actually executed shader may prove epoch, including upper 32 bits");
        if(spatial){const bool coarse=(!center&&iteration==1)||iteration==3||iteration==5||iteration==8;check(counts[0][1]==1&&counts[0][0]==unsigned(coarse),"Spatial map protects unknown, changed bindings, changing inputs, stale history and edges; stable tiles coarsen");auto map=control.spatial_readback();check(bool(map),"Spatial diagnostic readback");std::vector<GpuControl::SpatialTile> tiles;check(map->read(tiles)&&tiles.size()==1&&tiles[0].key==value.spatial_key&&tiles[0].frame==map->frame&&tiles[0].mode==(coarse?(mip?8u:2u):0u),"Readback map matches the actual executed tile policy");
            D3D12_RANGE range{0,4096};hr(pixels->Map(0,&range,&mapped));for(unsigned y=0;y<16;++y)for(unsigned x=0;x<16;++x){const auto sx=coarse&&!mip?x&~1u:x;const float input=iteration==6?(sx<8?.125f:.875f):iteration>=7?.125f:iteration>=4?.75f:.25f;const float sample=mip?(coarse?.5f:input):0;const float expected[]{input*sx+sample,input*y+sample,input+sample,input+sample};const auto* actual_pixel=static_cast<const float*>(mapped)+(y*16+x)*4;
                for(unsigned channel=0;channel<4;++channel)if(actual_pixel[channel]!=expected[channel]){std::cerr<<"iteration "<<iteration<<" pixel "<<x<<','<<y<<" channel "<<channel<<" actual "<<actual_pixel[channel]<<" expected "<<expected[channel]<<'\n';check(false,"Every spatial-policy output pixel matches independent CPU oracle");}}pixels->Unmap(0,&empty);
        }else held.push_back(*proof);
    }
    if(!spatial){arc::dx12::optimizer::ControlValue active{2,1,16,16};check(control.prepare(queue.Get(),{&active,1})==nullptr,"Pinned capture slots cannot be overwritten");
    std::array<std::array<UINT64,2>,GpuControl::capacity> original_marker{};check(held.front().read(original_marker)&&original_marker[0]==held.front().expected[0],"Captured marker remains immutable across reuse attempts");}
    for(UINT64 i=0;i<diagnostics->GetNumStoredMessages();++i){SIZE_T size{};hr(diagnostics->GetMessage(i,nullptr,&size));std::vector<char> storage(size);auto* message=reinterpret_cast<D3D12_MESSAGE*>(storage.data());hr(diagnostics->GetMessage(i,message,&size));if(message->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){std::cerr<<message->pDescription<<'\n';check(false,"Debug layer error");}}
    CloseHandle(event);std::cout<<(spatial?"Spatial importance, stale/changed input protection and every-pixel CPU oracle PASS\n":"GPU-written execution epoch, predication rejection, queue identity and pinned readback PASS\n");return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}
