#include <windows.h>
#include <d3d12.h>
#include <d3d12sdklayers.h>
#include <dxcapi.h>
#include <wrl/client.h>
#include "generic_shader_transform.hpp"
#include "generic_probe_transform.hpp"
#include "generic_binding_state.hpp"
#include "generic_gpu_control.hpp"
#include "generic_spatial_probe.hpp"
#include <filesystem>
#include <vector>
#include <array>
#include <cstring>
#include <iostream>
#include <stdexcept>
using Microsoft::WRL::ComPtr;
void require(bool ok,const char* message){if(!ok)throw std::runtime_error(message);}
void hr(HRESULT h){if(FAILED(h))throw std::runtime_error("HRESULT "+std::to_string(h));}
ComPtr<IDxcBlob> binary(IDxcOperationResult* operation){HRESULT status{};hr(operation->GetStatus(&status));if(FAILED(status)){ComPtr<IDxcBlobEncoding> errors;operation->GetErrorBuffer(&errors);if(errors)std::cerr.write(static_cast<const char*>(errors->GetBufferPointer()),errors->GetBufferSize());}hr(status);ComPtr<IDxcBlob> result;hr(operation->GetResult(&result));return result;}
struct Pixel {float r,g,b,a;};
int wmain(int argc,wchar_t** argv)try{
    require(argc==2,"Absolute compiler DLL required");const std::filesystem::path path=argv[1];
    auto validator_module=LoadLibraryExW((path.parent_path()/L"dxil.dll").c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);
    auto compiler_module=LoadLibraryExW(path.c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);require(compiler_module&&validator_module,"DXC load");
    auto create=reinterpret_cast<DxcCreateInstanceProc>(GetProcAddress(compiler_module,"DxcCreateInstance"));auto create_validator=reinterpret_cast<DxcCreateInstanceProc>(GetProcAddress(validator_module,"DxcCreateInstance"));
    ComPtr<IDxcLibrary> library;ComPtr<IDxcCompiler> compiler;ComPtr<IDxcAssembler> assembler;ComPtr<IDxcValidator> validator;
    hr(create(CLSID_DxcLibrary,IID_PPV_ARGS(&library)));hr(create(CLSID_DxcCompiler,IID_PPV_ARGS(&compiler)));hr(create(CLSID_DxcAssembler,IID_PPV_ARGS(&assembler)));hr(create_validator(CLSID_DxcValidator,IID_PPV_ARGS(&validator)));
    const std::string source=R"(Texture2D<float4> Input:register(t0);RWTexture2D<float4> Output:register(u0);RWTexture2D<float4> Aux:register(u1);
    [numthreads(8,8,1)]void main(uint3 p:SV_DispatchThreadID){float4 v=Input.Load(int3(p.xy,0));if(v.a==0){Aux[p.xy]=0;return;}Output[p.xy]=v*float4(p.x,p.y,1,1);Aux[p.xy]=float4(p.xy,0,1);})";
    ComPtr<IDxcBlobEncoding> text;hr(library->CreateBlobWithEncodingOnHeapCopy(source.data(),UINT(source.size()),CP_UTF8,&text));ComPtr<IDxcOperationResult> operation;hr(compiler->Compile(text.Get(),L"probe",L"main",L"cs_6_0",nullptr,0,nullptr,0,nullptr,&operation));auto original=binary(operation.Get());
    ComPtr<IDxcBlobEncoding> ir;hr(compiler->Disassemble(original.Get(),&ir));auto base=arc::dx12::shader::coarse_compute({static_cast<const char*>(ir->GetBufferPointer()),ir->GetBufferSize()},1,1,true,1,true);require(base.admitted,"Original transform");const auto probe=arc::dx12::shader::sparse_probe(base);require(probe.admitted&&probe.outputs==2,probe.reason.c_str());
    text.Reset();hr(library->CreateBlobWithEncodingOnHeapCopy(probe.ir.data(),UINT(probe.ir.size()),CP_UTF8,&text));operation.Reset();hr(assembler->AssembleToContainer(text.Get(),&operation));auto code=binary(operation.Get());operation.Reset();hr(validator->Validate(code.Get(),DxcValidatorFlags_InPlaceEdit,&operation));code=binary(operation.Get());
    ComPtr<ID3D12Debug> debug;hr(D3D12GetDebugInterface(IID_PPV_ARGS(&debug)));debug->EnableDebugLayer();ComPtr<ID3D12Device> device;hr(D3D12CreateDevice(nullptr,D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&device)));ComPtr<ID3D12InfoQueue> diagnostics;hr(device.As(&diagnostics));
    D3D12_DESCRIPTOR_RANGE ranges[]{{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,2,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,1,0,0,2}};D3D12_ROOT_PARAMETER parameter{};parameter.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;parameter.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC description{1,&parameter,0,nullptr,D3D12_ROOT_SIGNATURE_FLAG_NONE};ComPtr<ID3DBlob> root_bytes;hr(D3D12SerializeRootSignature(&description,D3D_ROOT_SIGNATURE_VERSION_1,&root_bytes,nullptr));
    auto extended=arc::dx12::binding::append_control_cbv({static_cast<const std::byte*>(root_bytes->GetBufferPointer()),root_bytes->GetBufferSize()},1,true,true);require(!extended.empty(),"Raw scratch root budget");ComPtr<ID3D12RootSignature> root;hr(device->CreateRootSignature(0,extended.data(),extended.size(),IID_PPV_ARGS(&root)));
    D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root.Get();pd.CS={code->GetBufferPointer(),code->GetBufferSize()};ComPtr<ID3D12PipelineState> pipeline;hr(device->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pipeline)));
    constexpr UINT width=61,height=37,pitch=1024;constexpr UINT64 texture_bytes=UINT64(pitch)*height,guard=256,scratch_bytes=32*32*2*32,buffer_bytes=guard+scratch_bytes*2;
    auto buffer=[&](UINT64 bytes,D3D12_HEAP_TYPE heap,D3D12_RESOURCE_STATES state,D3D12_RESOURCE_FLAGS flags){D3D12_HEAP_PROPERTIES hp{};hp.Type=heap;D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=bytes;d.Height=d.DepthOrArraySize=d.MipLevels=d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=flags;ComPtr<ID3D12Resource> r;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,state,nullptr,IID_PPV_ARGS(&r)));return r;};
    auto upload=buffer(texture_bytes*3,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE),scratch_upload=buffer(buffer_bytes,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE);
    auto scratch=buffer(buffer_bytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),readback=buffer(buffer_bytes,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_NONE),image_readback=buffer(texture_bytes*2,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_NONE);
    std::array<ComPtr<ID3D12Resource>,3> images;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC td{};td.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;td.Width=width;td.Height=height;td.DepthOrArraySize=td.MipLevels=td.SampleDesc.Count=1;td.Format=DXGI_FORMAT_R32G32B32A32_FLOAT;
    for(unsigned i=0;i<3;++i){td.Flags=i?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;hr(device->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&images[i])));}
    void* mapped{};D3D12_RANGE empty{};hr(upload->Map(0,&empty,&mapped));std::memset(mapped,0,SIZE_T(texture_bytes*3));for(unsigned i=0;i<3;++i)for(UINT y=0;y<height;++y)for(UINT x=0;x<width;++x){const Pixel p=i?Pixel{-32,-32,-32,-32}:Pixel{float(x)/64,float(y)/64,.25f,(x||y)?1.f:0.f};std::memcpy(static_cast<char*>(mapped)+i*texture_bytes+y*pitch+x*16,&p,16);}upload->Unmap(0,nullptr);hr(scratch_upload->Map(0,&empty,&mapped));std::memset(mapped,0xcd,SIZE_T(buffer_bytes));scratch_upload->Unmap(0,nullptr);
    D3D12_DESCRIPTOR_HEAP_DESC hd{};hd.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;hd.NumDescriptors=3;hd.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;ComPtr<ID3D12DescriptorHeap> heap;hr(device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));const auto increment=device->GetDescriptorHandleIncrementSize(hd.Type);auto handle=heap->GetCPUDescriptorHandleForHeapStart();for(unsigned i=1;i<3;++i){device->CreateUnorderedAccessView(images[i].Get(),nullptr,nullptr,handle);handle.ptr+=increment;}D3D12_SHADER_RESOURCE_VIEW_DESC srv{};srv.Format=td.Format;srv.ViewDimension=D3D12_SRV_DIMENSION_TEXTURE2D;srv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;srv.Texture2D.MipLevels=1;device->CreateShaderResourceView(images[0].Get(),&srv,handle);
    D3D12_COMMAND_QUEUE_DESC qd{};ComPtr<ID3D12CommandQueue> queue;hr(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)));ComPtr<ID3D12CommandAllocator> allocator;ComPtr<ID3D12GraphicsCommandList> list;hr(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)));hr(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),pipeline.Get(),IID_PPV_ARGS(&list)));
    auto transition=[&](ID3D12Resource* resource,D3D12_RESOURCE_STATES before,D3D12_RESOURCE_STATES after){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={resource,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,before,after};list->ResourceBarrier(1,&b);};
    for(unsigned i=0;i<3;++i){D3D12_TEXTURE_COPY_LOCATION dst{},src{};dst.pResource=images[i].Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;src.pResource=upload.Get();src.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;src.PlacedFootprint={i*texture_bytes,{td.Format,width,height,1,pitch}};list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);transition(images[i].Get(),D3D12_RESOURCE_STATE_COPY_DEST,i?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);}list->CopyResource(scratch.Get(),scratch_upload.Get());transition(scratch.Get(),D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);hr(list->Close());
    ComPtr<ID3D12Fence> fence;hr(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)));HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);UINT64 serial=0;
    auto finish=[&]{hr(queue->Signal(fence.Get(),++serial));hr(fence->SetEventOnCompletion(serial,event));require(WaitForSingleObject(event,5000)==WAIT_OBJECT_0,"GPU completion");};
    ID3D12CommandList* work[]{list.Get()};queue->ExecuteCommandLists(1,work);finish();arc::dx12::optimizer::GpuControl control(device.Get());
    for(unsigned test=0;test<3;++test){const UINT rate=test==1?4:1,tile=rate==4?32:16,phase=test==2?11:0;const UINT64 epoch=UINT64(0x1234567800000000)+test+1;
        hr(allocator->Reset());hr(list->Reset(allocator.Get(),pipeline.Get()));ID3D12DescriptorHeap* heaps[]{heap.Get()};list->SetDescriptorHeaps(1,heaps);list->SetComputeRootSignature(root.Get());list->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());list->SetComputeRootConstantBufferView(1,control.address(0));list->SetComputeRootUnorderedAccessView(2,control.marker_address(0));list->SetComputeRootUnorderedAccessView(3,scratch->GetGPUVirtualAddress()+guard);list->Dispatch((width+7)/8,(height+7)/8,1);control.record_neutralize(list.Get());
        transition(scratch.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);list->CopyResource(readback.Get(),scratch.Get());transition(scratch.Get(),D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
        for(unsigned i=1;i<3;++i){transition(images[i].Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE);D3D12_TEXTURE_COPY_LOCATION dst{},src{};dst.pResource=image_readback.Get();dst.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;dst.PlacedFootprint={(i-1)*texture_bytes,{td.Format,width,height,1,pitch}};src.pResource=images[i].Get();src.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;list->CopyTextureRegion(&dst,0,0,0,&src,nullptr);transition(images[i].Get(),D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);}hr(list->Close());
        arc::dx12::optimizer::ControlValue value{rate,rate,width,height};value.probe_epoch=epoch;value.probe_phase=phase;value.spatial_tile_width=value.spatial_tile_height=tile;auto* helper=control.prepare(queue.Get(),{&value,1});require(helper,"Probe upload");queue->ExecuteCommandLists(1,&helper);queue->ExecuteCommandLists(1,work);control.submitted(queue.Get());finish();
        D3D12_RANGE range{0,SIZE_T(buffer_bytes)};hr(readback->Map(0,&range,&mapped));const auto* raw=static_cast<const unsigned char*>(mapped);for(UINT64 i=0;i<guard;++i)require(raw[i]==0xcd,"Leading guard");for(UINT64 i=guard+scratch_bytes;i<buffer_bytes;++i)require(raw[i]==0xcd,"Trailing guard");const UINT columns=(width+tile-1)/tile,ox=(phase%columns)*tile,oy=(phase/columns)*tile;
        for(UINT y=0;y<tile&&y+oy<height;++y)for(UINT x=0;x<tile&&x+ox<width;++x)for(unsigned output=0;output<2;++output){const auto offset=guard+((y*tile+x)*2+output)*32;UINT64 written_epoch{};UINT mask{};Pixel actual{};std::memcpy(&actual,raw+offset,16);std::memcpy(&written_epoch,raw+offset+16,8);std::memcpy(&mask,raw+offset+24,4);require(written_epoch==epoch,"Fresh full-width epoch, including omitted writes");const UINT sx=ox+x/rate*rate,sy=oy+y/rate*rate;const bool writes=output||sx||sy;require(mask==(writes?15u:0u),"Per-output coverage mask reset");if(writes){const Pixel expected=(sx||sy)?(output?Pixel{float(sx),float(sy),0,1}:Pixel{float(sx*sx)/64,float(sy*sy)/64,.25f,1}):Pixel{};require(std::memcmp(&actual,&expected,16)==0,"Sparse same-input raw CPU oracle");}}
        readback->Unmap(0,&empty);range={0,SIZE_T(texture_bytes*2)};hr(image_readback->Map(0,&range,&mapped));for(unsigned i=0;i<2;++i)for(UINT y=0;y<height;++y)for(UINT x=0;x<width*4;++x)require(*reinterpret_cast<const float*>(static_cast<const char*>(mapped)+i*texture_bytes+y*pitch+x*4)==-32,"Probe must not touch application outputs");image_readback->Unmap(0,&empty);
    }
    arc::dx12::optimizer::SpatialProbeGpu comparison(device.Get(),scratch_bytes);
    for(unsigned test=0;test<3;++test){const auto epoch=UINT64(0x9876543200000000)+test+1;require(comparison.reserve(epoch),"Reserve fresh probe");require(!comparison.collect(),"Unsubmitted epoch cannot read previous results");
        hr(allocator->Reset());hr(list->Reset(allocator.Get(),pipeline.Get()));ID3D12DescriptorHeap* heaps[]{heap.Get()};list->SetDescriptorHeaps(1,heaps);
        for(unsigned which=0;which<2;++which){list->SetPipelineState(pipeline.Get());list->SetComputeRootSignature(root.Get());list->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());list->SetComputeRootConstantBufferView(1,control.address(which));list->SetComputeRootUnorderedAccessView(2,control.marker_address(which));list->SetComputeRootUnorderedAccessView(3,which?comparison.candidate_address():comparison.reference_address());list->Dispatch((width+7)/8,(height+7)/8,1);}
        comparison.record_compare(list.Get(),control.address(1),control.marker_address(1),2,false);control.record_neutralize(list.Get());hr(list->Close());
        std::array<arc::dx12::optimizer::ControlValue,2> values;for(auto& v:values){v.width=width;v.height=height;v.probe_epoch=epoch;v.probe_phase=test==2?0:11;v.spatial_tile_width=v.spatial_tile_height=16;}if(test)values[1].x=values[1].y=2;
        auto* helper=control.prepare(queue.Get(),values);require(helper,"Comparison control upload");queue->ExecuteCommandLists(1,&helper);queue->ExecuteCommandLists(1,work);control.submitted(queue.Get());comparison.submitted(queue.Get());finish();const auto observation=comparison.collect();require(observation&&observation->epoch==epoch&&observation->outputs==2,"Completed GPU pair identity");require(!comparison.collect(),"Results consumed exactly once");require(!comparison.reserve(epoch),"Epoch reuse rejected");
        if(test==2)require(observation->bins[0].invalid_tiles>0&&observation->bins[0].valid_tiles==0,"Different omitted-write coverage must reject a tile");
        else{require(observation->bins[0].valid_tiles==1&&observation->bins[0].invalid_tiles==0,"One selected edge tile, complete pair");float error{};std::memcpy(&error,&observation->bins[0].error_bits,4);require(test?error>0:error==0,"Neutral noise zero and actual candidate error measured");}
    }
    for(UINT64 i=0;i<diagnostics->GetNumStoredMessages();++i){SIZE_T size{};hr(diagnostics->GetMessage(i,nullptr,&size));std::vector<char> bytes(size);auto* m=reinterpret_cast<D3D12_MESSAGE*>(bytes.data());hr(diagnostics->GetMessage(i,m,&size));if(m->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){std::cerr<<m->pDescription<<'\n';require(false,"Debug layer error");}}
    CloseHandle(event);std::cout<<"Sparse raw probes: two outputs, neutral/4x, epoch/masks, edge tiles, untouched app outputs and guards PASS\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}
