// Mechanical forwarding from Windows SDK 10.0.26100.0.
HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID Name, UINT DataSize, const void *pData) override { ARC2_CPU_SCOPE(DXGI_SetPrivateData); return ARC2_APP_CALL(native_, SetPrivateData, Name, DataSize, pData); }
HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID Name, UINT *pDataSize, void *pData) override { ARC2_CPU_SCOPE(DXGI_GetPrivateData); return ARC2_APP_CALL(native_, GetPrivateData, Name, pDataSize, pData); }
HRESULT STDMETHODCALLTYPE GetParent(REFIID riid, void **ppParent) override { ARC2_CPU_SCOPE(DXGI_GetParent); return ARC2_APP_CALL(native_, GetParent, riid, ppParent); }
HRESULT STDMETHODCALLTYPE EnumAdapters(UINT Adapter, IDXGIAdapter **ppAdapter) override { ARC2_CPU_SCOPE(DXGI_EnumAdapters); return ARC2_APP_CALL(native_, EnumAdapters, Adapter, ppAdapter); }
HRESULT STDMETHODCALLTYPE MakeWindowAssociation(HWND WindowHandle, UINT Flags) override { ARC2_CPU_SCOPE(DXGI_MakeWindowAssociation); return ARC2_APP_CALL(native_, MakeWindowAssociation, WindowHandle, Flags); }
HRESULT STDMETHODCALLTYPE GetWindowAssociation(HWND *pWindowHandle) override { ARC2_CPU_SCOPE(DXGI_GetWindowAssociation); return ARC2_APP_CALL(native_, GetWindowAssociation, pWindowHandle); }
HRESULT STDMETHODCALLTYPE CreateSoftwareAdapter(HMODULE Module, IDXGIAdapter **ppAdapter) override { ARC2_CPU_SCOPE(DXGI_CreateSoftwareAdapter); return ARC2_APP_CALL(native_, CreateSoftwareAdapter, Module, ppAdapter); }
HRESULT STDMETHODCALLTYPE EnumAdapters1(UINT Adapter, IDXGIAdapter1 **ppAdapter) override { ARC2_CPU_SCOPE(DXGI_EnumAdapters1); return ARC2_APP_CALL(native_, EnumAdapters1, Adapter, ppAdapter); }
BOOL STDMETHODCALLTYPE IsCurrent(void) override { ARC2_CPU_SCOPE(DXGI_IsCurrent); return ARC2_APP_CALL(native_, IsCurrent); }
BOOL STDMETHODCALLTYPE IsWindowedStereoEnabled(void) override { ARC2_CPU_SCOPE(DXGI_IsWindowedStereoEnabled); return ARC2_APP_CALL(native_, IsWindowedStereoEnabled); }
HRESULT STDMETHODCALLTYPE GetSharedResourceAdapterLuid(HANDLE hResource, LUID *pLuid) override { ARC2_CPU_SCOPE(DXGI_GetSharedResourceAdapterLuid); return ARC2_APP_CALL(native_, GetSharedResourceAdapterLuid, hResource, pLuid); }
HRESULT STDMETHODCALLTYPE RegisterStereoStatusWindow(HWND WindowHandle, UINT wMsg, DWORD *pdwCookie) override { ARC2_CPU_SCOPE(DXGI_RegisterStereoStatusWindow); return ARC2_APP_CALL(native_, RegisterStereoStatusWindow, WindowHandle, wMsg, pdwCookie); }
HRESULT STDMETHODCALLTYPE RegisterStereoStatusEvent(HANDLE hEvent, DWORD *pdwCookie) override { ARC2_CPU_SCOPE(DXGI_RegisterStereoStatusEvent); return ARC2_APP_CALL(native_, RegisterStereoStatusEvent, hEvent, pdwCookie); }
void STDMETHODCALLTYPE UnregisterStereoStatus(DWORD dwCookie) override { ARC2_CPU_SCOPE(DXGI_UnregisterStereoStatus); return ARC2_APP_CALL(native_, UnregisterStereoStatus, dwCookie); }
HRESULT STDMETHODCALLTYPE RegisterOcclusionStatusWindow(HWND WindowHandle, UINT wMsg, DWORD *pdwCookie) override { ARC2_CPU_SCOPE(DXGI_RegisterOcclusionStatusWindow); return ARC2_APP_CALL(native_, RegisterOcclusionStatusWindow, WindowHandle, wMsg, pdwCookie); }
HRESULT STDMETHODCALLTYPE RegisterOcclusionStatusEvent(HANDLE hEvent, DWORD *pdwCookie) override { ARC2_CPU_SCOPE(DXGI_RegisterOcclusionStatusEvent); return ARC2_APP_CALL(native_, RegisterOcclusionStatusEvent, hEvent, pdwCookie); }
void STDMETHODCALLTYPE UnregisterOcclusionStatus(DWORD dwCookie) override { ARC2_CPU_SCOPE(DXGI_UnregisterOcclusionStatus); return ARC2_APP_CALL(native_, UnregisterOcclusionStatus, dwCookie); }
UINT STDMETHODCALLTYPE GetCreationFlags(void) override { ARC2_CPU_SCOPE(DXGI_GetCreationFlags); return ARC2_APP_CALL(native_, GetCreationFlags); }
HRESULT STDMETHODCALLTYPE EnumAdapterByLuid(LUID AdapterLuid, REFIID riid, void **ppvAdapter) override { ARC2_CPU_SCOPE(DXGI_EnumAdapterByLuid); return ARC2_APP_CALL(native_, EnumAdapterByLuid, AdapterLuid, riid, ppvAdapter); }
HRESULT STDMETHODCALLTYPE EnumWarpAdapter(REFIID riid, void **ppvAdapter) override { ARC2_CPU_SCOPE(DXGI_EnumWarpAdapter); return ARC2_APP_CALL(native_, EnumWarpAdapter, riid, ppvAdapter); }
HRESULT STDMETHODCALLTYPE CheckFeatureSupport(DXGI_FEATURE Feature, void *pFeatureSupportData, UINT FeatureSupportDataSize) override { ARC2_CPU_SCOPE(DXGI_CheckFeatureSupport); return ARC2_APP_CALL(native_, CheckFeatureSupport, Feature, pFeatureSupportData, FeatureSupportDataSize); }
HRESULT STDMETHODCALLTYPE EnumAdapterByGpuPreference(UINT Adapter, DXGI_GPU_PREFERENCE GpuPreference, REFIID riid, void **ppvAdapter) override { ARC2_CPU_SCOPE(DXGI_EnumAdapterByGpuPreference); return ARC2_APP_CALL(native_, EnumAdapterByGpuPreference, Adapter, GpuPreference, riid, ppvAdapter); }
HRESULT STDMETHODCALLTYPE RegisterAdaptersChangedEvent(HANDLE hEvent, DWORD *pdwCookie) override { ARC2_CPU_SCOPE(DXGI_RegisterAdaptersChangedEvent); return ARC2_APP_CALL(native_, RegisterAdaptersChangedEvent, hEvent, pdwCookie); }
HRESULT STDMETHODCALLTYPE UnregisterAdaptersChangedEvent(DWORD dwCookie) override { ARC2_CPU_SCOPE(DXGI_UnregisterAdaptersChangedEvent); return ARC2_APP_CALL(native_, UnregisterAdaptersChangedEvent, dwCookie); }
