option(ARC2_FRONTEND "Build the ARC2 semantic D3D12 frontend" ON)
if(ARC2_FRONTEND)
  add_library(arc2-ir STATIC src/arc2/runtime.cpp src/arc2/ir.cpp src/arc2/bridge.cpp)
  target_include_directories(arc2-ir PUBLIC include)
  target_link_libraries(arc2-ir PUBLIC arc-core)
  if(ARC_BUILD_TESTS)
    add_executable(arc2-ir-tests tests/arc2_ir_tests.cpp)
    target_link_libraries(arc2-ir-tests PRIVATE arc2-ir)
    if(MSVC)
      target_compile_options(arc2-ir-tests PRIVATE /UNDEBUG)
    endif()
    add_test(NAME arc2-ir-tests COMMAND arc2-ir-tests)
  endif()
endif()
