option(ARC2_FRONTEND "Build the ARC2 semantic D3D12 frontend" ON)
if(ARC2_FRONTEND)
  add_library(arc2-ir STATIC src/arc2/runtime.cpp src/arc2/ir.cpp src/arc2/bridge.cpp)
  target_include_directories(arc2-ir PUBLIC include)
  target_link_libraries(arc2-ir PUBLIC arc-core)
  if(ARC_BUILD_TESTS)
    add_executable(arc2-ir-tests tests/arc2_ir_tests.cpp)
    target_link_libraries(arc2-ir-tests PRIVATE arc2-ir)
    if(MSVC)
      target_compile_options(arc2-ir-tests PRIVATE /UNDEBUG)
    endif()
    add_test(NAME arc2-ir-tests COMMAND arc2-ir-tests)
  endif()
  if(WIN32)
    add_library(arc2-frontend SHARED src/arc2/frontend.cpp src/arc2/dxgi.cpp src/arc2/rewriter.cpp src/arc2/observe.cpp src/arc2/diagnostics.cpp src/arc2/shader_semantics.cpp src/arc2/present_metrics.cpp src/arc2/root_signature.cpp src/arc2/fixed_pipeline.cpp)
    target_include_directories(arc2-frontend PRIVATE include src/arc2)
    target_compile_definitions(arc2-frontend PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(arc2-frontend PRIVATE arc2-ir d3d12 dxgi d3dcompiler bcrypt)
    add_executable(arc2-quality-check tests/arc2_quality_check.cpp)
    target_link_libraries(arc2-quality-check PRIVATE arc-core)
    add_executable(arc2-binding-native tests/arc2_binding_native.cpp)
    target_include_directories(arc2-binding-native PRIVATE include)
    target_link_libraries(arc2-binding-native PRIVATE d3d12 dxgi d3dcompiler)
    add_executable(arc2-native-lab tests/arc2_native_lab.cpp)
    target_include_directories(arc2-native-lab PRIVATE include)
    target_compile_definitions(arc2-native-lab PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(arc2-native-lab PRIVATE d3d12 dxgi d3dcompiler user32 arc-core)
    if(ARC_BUILD_TESTS AND ARC_GPU_TESTS)
      add_test(NAME arc2-native-passthrough COMMAND arc2-native-lab "${CMAKE_BINARY_DIR}/arc2-passthrough" 16 24 debug)
      add_test(NAME arc2-native-rollback COMMAND arc2-native-lab "${CMAKE_BINARY_DIR}/arc2-rollback" 16 24 debug toggle)
      add_test(NAME arc2-native-bindings COMMAND arc2-binding-native)
      foreach(test arc2-native-passthrough arc2-native-rollback arc2-native-bindings)
        set_tests_properties(${test} PROPERTIES LABELS gpu TIMEOUT 60 RUN_SERIAL TRUE
          ENVIRONMENT "ARC1_DLL=;ARC2_MODE=passthrough;ARC2_DLL=$<TARGET_FILE:arc2-frontend>;ARC2_OUTPUT=${CMAKE_BINARY_DIR}/${test}.json")
      endforeach()
      set_tests_properties(arc2-native-rollback PROPERTIES ENVIRONMENT "ARC1_DLL=;ARC2_MODE=optimize;ARC2_DLL=$<TARGET_FILE:arc2-frontend>;ARC2_OUTPUT=${CMAKE_BINARY_DIR}/arc2-native-rollback.json")
    endif()
  endif()
endif()
