target_sources(arc-core PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src/core/perceptual_trial.cpp)
if(ARC_BUILD_TESTS)
    add_executable(arc-perceptual-trial-tests ${CMAKE_CURRENT_SOURCE_DIR}/tests/perceptual_trial_tests.cpp)
    target_link_libraries(arc-perceptual-trial-tests PRIVATE arc::core)
    add_test(NAME arc-perceptual-trial-tests COMMAND arc-perceptual-trial-tests)
endif()
if(WIN32 AND ARC_BUILD_TESTS)
    add_executable(arc-full-frame-x2 ${CMAKE_CURRENT_SOURCE_DIR}/samples/full_frame_x2.cpp)
    target_compile_definitions(arc-full-frame-x2 PRIVATE NOMINMAX)
    target_link_libraries(arc-full-frame-x2 PRIVATE arc::core d3d12 dxgi d3dcompiler user32)
    add_executable(arc-perceptual-native ${CMAKE_CURRENT_SOURCE_DIR}/tests/perceptual_native.cpp)
    target_link_libraries(arc-perceptual-native PRIVATE arc::core d3d12 dxgi d3dcompiler)
    if(ARC_GPU_TESTS)
        add_test(NAME arc-perceptual-native COMMAND arc-perceptual-native)
        set_tests_properties(arc-perceptual-native PROPERTIES LABELS gpu TIMEOUT 120 RUN_SERIAL TRUE)
    endif()
endif()
