// Training-only callback-loop boundaries. No TF stepping into the callback.
#include <windows.h>
#include <atomic>
#include <filesystem>
#include <fstream>
#include <vector>
#include <iomanip>
#include <algorithm>
namespace {
struct Op{int kind;uint64_t value;};struct Row{uint32_t index,arg_index;uint64_t begin,end,input,output,producer_qpc;bool ok,seen;unsigned char before[64],ready[64],after[64],value[32];};
struct Group{DWORD tid;uint32_t first,last,count,atomic_old;uint64_t descriptor,stack,counter,begin,end;bool complete,inflight;Row rows[1024];};
static Group groups[3];static unsigned producerInputReg,producerOutputReg,producerConditionReg;static int64_t producerOutputDisp;static uint64_t producerConditionValue;
static unsigned wanted,maxElements,waitMs,indexReg,descriptorReg,inputBytes,outputBytes,indexOffset,chainN,outN,inN;static uintptr_t pc[4],callback,expectedOut,expectedIn;static int64_t startOffset,endOffset,counterOffset,argAdjust;static uint64_t outputStride,inputStride,chain[4];static Op outOps[32],inOps[32];static std::vector<DWORD> tids,armed;static std::filesystem::path folder;static std::atomic<DWORD> owner{};static std::atomic<unsigned> done{},inside{},skips{};static std::atomic<bool> stop{};static unsigned failure{};static LONGLONG frequency,start;
using GS=LONG(NTAPI*)();using SS=void(NTAPI*)(LONG);static GS getStatus;static SS setStatus;
uint64_t now(){LARGE_INTEGER n;QueryPerformanceCounter(&n);return n.QuadPart;}
uint64_t reg(const CONTEXT& c,unsigned i){uint64_t r[]={c.Rax,c.Rcx,c.Rdx,c.Rbx,c.Rsp,c.Rbp,c.Rsi,c.Rdi,c.R8,c.R9,c.R10,c.R11,c.R12,c.R13,c.R14,c.R15};return r[i];}
bool read(uint64_t p,void* b,size_t n){SIZE_T got{};return ReadProcessMemory(GetCurrentProcess(),(void*)p,b,n,&got)&&got==n;}
bool eval(Op* ops,unsigned n,uint64_t arg,uint64_t& answer){uint64_t values[32];unsigned size=0;for(unsigned i=0;i<n;++i){auto o=ops[i];if(o.kind==0)values[size++]=o.value;else if(o.kind==1)values[size++]=arg;else if(o.kind==4){if(!size||!read(values[size-1],values+size-1,8))return false;}else{if(size<2)return false;auto b=values[--size];if(o.kind==2)values[size-1]+=b;else if(o.kind==3)values[size-1]*=b;else return false;}if(size>=32)return false;}if(size!=1)return false;answer=values[0];return true;}
void clear(CONTEXT* c){if(c->Dr0==pc[0]){c->Dr0=0;c->Dr7&=~uint64_t(0xf0003);}if(c->Dr1==pc[1]){c->Dr1=0;c->Dr7&=~uint64_t(0xf0000c);}if(c->Dr2==pc[2]){c->Dr2=0;c->Dr7&=~uint64_t(0xf000030);}if(c->Dr3==pc[3]){c->Dr3=0;c->Dr7&=~uint64_t(0xf00000c0);}c->Dr6&=~uint64_t(15);}
LONG CALLBACK handler(EXCEPTION_POINTERS* e){auto* c=e->ContextRecord;if(e->ExceptionRecord->ExceptionCode!=EXCEPTION_SINGLE_STEP)return EXCEPTION_CONTINUE_SEARCH;DWORD tid=GetCurrentThreadId();int hit=-1;for(int i=0;i<4;++i)if(c->Rip==pc[i]&&(c->Dr6&(1ull<<i)))hit=i;if(hit<0||std::find(tids.begin(),tids.end(),tid)==tids.end())return EXCEPTION_CONTINUE_SEARCH;
 auto error=GetLastError();auto status=getStatus();++inside;
 if(stop)clear(c);
 else if(hit==0){uint64_t desc=reg(*c,descriptorReg),fn=desc,arg=0,ob=0,ib=0;uint32_t first=0,last=0;bool ok=read(desc+startOffset,&first,4)&&read(desc+endOffset,&last,4)&&last>first&&last-first<=maxElements;
  for(unsigned i=0;i<chainN&&ok;++i){ok=read(fn+chain[i],&fn,8);if(i==0)arg=fn+argAdjust;}
  ok=ok&&fn==callback&&eval(outOps,outN,arg,ob)&&eval(inOps,inN,arg,ib)&&ob==expectedOut&&ib==expectedIn&&uint32_t(reg(*c,indexReg))==first;
  DWORD zero=0;if(ok&&owner.compare_exchange_strong(zero,tid)){if(stop)owner=0;else{auto& g=groups[done];g.tid=tid;g.first=first;g.last=last;g.descriptor=desc;g.stack=c->Rsp;g.begin=now();read(desc+counterOffset,&g.counter,8);}}else ++skips;
 }else if(owner==tid){auto& g=groups[done];
  if(hit==2){auto& r=g.rows[g.count];if(!g.inflight||r.seen||reg(*c,producerInputReg)!=r.input||reg(*c,producerOutputReg)+producerOutputDisp!=r.output||reg(*c,producerConditionReg)!=producerConditionValue){failure=4;stop=true;}else{r.seen=true;r.producer_qpc=now();r.ok=r.ok&&read(r.input,r.ready,inputBytes);}}
  else if(c->Rsp==g.stack&&reg(*c,descriptorReg)==g.descriptor){uint32_t index=uint32_t(reg(*c,indexReg));
   auto finish=[&](){if(!g.inflight)return;auto& r=g.rows[g.count];r.end=now();r.ok=r.ok&&r.seen&&read(r.input,r.after,inputBytes)&&read(r.output,r.value,outputBytes);if(!r.ok){failure=2;stop=true;}else ++g.count;g.inflight=false;};
   if(hit==1){finish();if(!stop){if(index!=g.first+g.count||g.count>=maxElements){failure=1;stop=true;}else{auto& r=g.rows[g.count];r.index=index;r.begin=now();r.input=expectedIn+uint64_t(index)*inputStride;r.output=expectedOut+uint64_t(index)*outputStride;r.ok=read(c->Rdx+indexOffset,&r.arg_index,4)&&read(r.input,r.before,inputBytes)&&r.arg_index==index;g.inflight=true;}}}
   if(hit==3){finish();g.end=now();g.atomic_old=uint32_t(c->Rax);g.complete=!stop&&index==g.last&&g.count==g.last-g.first;if(!g.complete){failure=3;stop=true;}else if(++done>=wanted)stop=true;owner=0;}
  }
 }

 if(stop)clear(c);c->Dr6&=~uint64_t(15);c->EFlags|=0x10000u;--inside;setStatus(status);SetLastError(error);return EXCEPTION_CONTINUE_EXECUTION;}
bool configure(DWORD tid,bool enable){auto h=OpenThread(THREAD_SUSPEND_RESUME|THREAD_GET_CONTEXT|THREAD_SET_CONTEXT,FALSE,tid);if(!h)return false;bool ok=false;if(SuspendThread(h)!=DWORD(-1)){CONTEXT c{};c.ContextFlags=CONTEXT_DEBUG_REGISTERS;if(GetThreadContext(h,&c)){if(enable){if(!(c.Dr7&255)){c.Dr0=pc[0];c.Dr1=pc[1];c.Dr2=pc[2];c.Dr3=pc[3];c.Dr7=(c.Dr7&~uint64_t(0xffff00ff))|0x55;ok=SetThreadContext(h,&c)!=FALSE;}}else{clear(&c);ok=SetThreadContext(h,&c)!=FALSE;}}ResumeThread(h);}CloseHandle(h);return ok;}
void hex(std::ostream& f,const void* p,size_t n){auto b=(const unsigned char*)p;for(size_t i=0;i<n;++i)f<<std::hex<<std::setw(2)<<std::setfill('0')<<unsigned(b[i]);f<<std::dec;}
DWORD WINAPI worker(void*){LARGE_INTEGER q;QueryPerformanceFrequency(&q);frequency=q.QuadPart;start=now();AddVectoredExceptionHandler(1,handler);for(auto tid:tids)if(configure(tid,true))armed.push_back(tid);while(!stop&&double(now()-start)*1000/frequency<waitMs){if(std::filesystem::exists(folder/L"cancel"))stop=true;Sleep(1);}stop=true;unsigned restored=0;for(auto tid:armed)restored+=configure(tid,false);while(inside)Sleep(1);
 std::ofstream f(folder/L"groups.json");f<<'[';for(unsigned j=0;j<done;++j){auto& g=groups[j];if(j)f<<',';f<<"{\"tid\":"<<g.tid<<",\"start\":"<<g.first<<",\"end\":"<<g.last<<",\"counter_address\":"<<g.counter<<",\"atomic_old\":"<<g.atomic_old<<",\"begin_qpc\":"<<g.begin<<",\"end_qpc\":"<<g.end<<",\"rows\":[";for(unsigned i=0;i<g.count;++i){auto& r=g.rows[i];if(i)f<<',';f<<"{\"index\":"<<r.index<<",\"argument_index\":"<<r.arg_index<<",\"input_address\":"<<r.input<<",\"output_address\":"<<r.output<<",\"callback_begin_qpc\":"<<r.begin<<",\"callback_end_qpc\":"<<r.end<<",\"input_before\":\"";hex(f,r.before,inputBytes);f<<"\",\"input_ready\":\"";hex(f,r.ready,inputBytes);f<<"\",\"producer_qpc\":"<<r.producer_qpc<<",\"input_after\":\"";hex(f,r.after,inputBytes);f<<"\",\"output_after\":\"";hex(f,r.value,outputBytes);f<<"\"}";}f<<"]}";}f<<']';f.close();std::ofstream meta(folder/L"done.json");meta<<"{\"groups\":"<<done<<",\"failure\":"<<failure<<",\"skipped_entries\":"<<skips<<",\"armed\":"<<armed.size()<<",\"restored\":"<<restored<<",\"elapsed_ms\":"<<double(now()-start)*1000/frequency<<",\"allocated_event_bytes\":"<<sizeof(groups)<<",\"replacement_enabled\":false}";return 0;}
}
extern "C" __declspec(dllexport) DWORD WINAPI ArcInitialize(void* path){if(!path||pc[0]||IsDebuggerPresent())return 1;folder=std::filesystem::path((wchar_t*)path).parent_path();std::ifstream f(folder/L"batch.txt");for(auto& p:pc)f>>p;unsigned n;f>>indexReg>>descriptorReg>>startOffset>>endOffset>>callback>>counterOffset>>producerInputReg>>producerOutputReg>>producerOutputDisp>>producerConditionReg>>producerConditionValue>>argAdjust>>indexOffset>>expectedOut>>expectedIn>>outputStride>>inputStride>>inputBytes>>outputBytes>>wanted>>maxElements>>waitMs>>n;if(!f||indexReg>15||descriptorReg>15||producerInputReg>15||producerOutputReg>15||producerConditionReg>15||n>16||!wanted||wanted>3||!maxElements||maxElements>1024||!inputBytes||inputBytes>64||!outputBytes||outputBytes>32||waitMs>10000)return 2;for(unsigned i=0;i<n;++i){DWORD t;f>>t;tids.push_back(t);}f>>chainN;if(!chainN||chainN>4)return 3;for(unsigned i=0;i<chainN;++i)f>>chain[i];f>>outN;if(!outN||outN>32)return 3;for(unsigned i=0;i<outN;++i)f>>outOps[i].kind>>outOps[i].value;f>>inN;if(!inN||inN>32)return 3;for(unsigned i=0;i<inN;++i)f>>inOps[i].kind>>inOps[i].value;if(!f)return 4;auto nt=GetModuleHandleW(L"ntdll.dll");getStatus=(GS)GetProcAddress(nt,"RtlGetLastNtStatus");setStatus=(SS)GetProcAddress(nt,"RtlSetLastWin32ErrorAndNtStatusFromNtStatus");if(!getStatus||!setStatus)return 5;HANDLE h=CreateThread(nullptr,0,worker,nullptr,0,nullptr);if(!h)return 6;CloseHandle(h);return 0;}
extern "C" __declspec(dllexport) DWORD WINAPI ArcCaptureBytes(void*){return sizeof(groups);}
extern "C" __declspec(dllexport) DWORD WINAPI ArcStopOptimizer(void*){stop=true;return 0;}
BOOL WINAPI DllMain(HINSTANCE h,DWORD why,void*){if(why==DLL_PROCESS_ATTACH)DisableThreadLibraryCalls(h);return TRUE;}
